// <auto-generated />
using System;
using BikeRentalApp.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BikeRentalApp.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241215234625_AddEntregadoresTable")]
    partial class AddEntregadoresTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BikeRentalApp.Domain.Entities.Entregador", b =>
                {
                    b.Property<string>("Identificador")
                        .HasColumnType("text");

                    b.Property<string>("CNPJ")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Data_Nascimento")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Imagem_CNH")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Numero_CNH")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tipo_CNH")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Identificador");

                    b.HasIndex("CNPJ")
                        .IsUnique();

                    b.HasIndex("Numero_CNH")
                        .IsUnique();

                    b.ToTable("Entregadores");
                });

            modelBuilder.Entity("BikeRentalApp.Domain.Entities.Moto", b =>
                {
                    b.Property<string>("Identificador")
                        .HasColumnType("text");

                    b.Property<int>("Ano")
                        .HasColumnType("integer");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Identificador");

                    b.HasIndex("Placa")
                        .IsUnique();

                    b.ToTable("Motos");
                });
#pragma warning restore 612, 618
        }
    }
}
